### ISSUE TITLE
crash on demo pipeline

### ISSUE THREAD

**Issue by luismavs** [lucafaggianelli/plombery#128]
Hi,
Great idea and nice project : )

Experimenting with version 0.3.1, I followed the tutorial to create a very basic pipeline (copying your script to 

https://lucafaggianelli.github.io/plombery/create-a-pipeline/

I get a crash when clicking on the Run button.

```
INFO:     127.0.0.1:50624 - "GET /runs HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[List[plombery.schemas.TaskRun]]
__root__ -> 0 -> duration
  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)
```

I then have to delete the plombery.db file to reset it.

Interestingly if I install plombery on a python 3.10 env, this only happens after clicking the Run button some 6 times (each time after I press I have to refresh the page to be able to re press it).

I'm running on conda envs in a mac os.

**Comment by lucafaggianelli** [comment]
ah for the dialog problem I opened the issue #133 thanks for that as well!
