### ISSUE TITLE
is it possible to add a startup event to the app?

### ISSUE THREAD

**Issue by serensoner** [lucafaggianelli/plombery#143]
hi, i want to add a startup event to the fastapi itself, is it possible to do that, or should i just do 

```
from plombery import app as fastapi_app
@fastapi_app.on_event("startup")
async def do_my_stuff():
    pass
```

**Comment by lucafaggianelli** [comment]
Hi,

For the moment that's the only way to do it, though it looks clean to me

**Comment by lucafaggianelli** [comment]
I'm closing this, but feel free to re-open/comment if you think we should implement a better solution 😃
