### ISSUE TITLE
How to change timezone?

### ISSUE THREAD

**Issue by mrhaa** [lucafaggianelli/plombery#151]
In v0.3.2, every times on the plombery saved with UTC timezone.

Can I change UST to KST?

BTW, Thanks for the awesome work!

**Comment by lucafaggianelli** [comment]
Yeah I decided to store dates and times as UTC to avoid issues, both in the database and also in the logs, though in the ui I show the local time, based on the browser time zone.

So you want to store datetimes with the local timezone or it's just a matter of visualisation?

I think I can add a setting for explicitly setting a TZ but I wouldn't rely on the default tz of the machine where plombery is running as it may be a mess, ie on your laptop it's your local time but on the server it's typically utc
