### ISSUE TITLE
Is it possible to add a pipeline to a running Uvicorn

### ISSUE THREAD

**Issue by thebruuu** [lucafaggianelli/plombery#164]
Once a Uvicorn app runs and Plombery Web server is running
Is there a way to add Pipelines? Or should I stop the server, add an import in the main app py and run it?

**Comment by thebruuu** [comment]
Sorry man

**Comment by lucafaggianelli** [comment]
> Sorry man

For what? 🙂

yes you can add pipeline at runtime, just call `register_pipeline` like in the examples 

Let me know if you have any issue
