### ISSUE TITLE
Reset Database

### ISSUE THREAD

**Issue by thebruuu** [lucafaggianelli/plombery#237]
After a Pc reboot,

Plombery isn't showing anymore the tasks.
I fear an hard stop compromised Plombery Stabilty.
I need then to reset Plombery : Of course I could create another environment and copy the tasks into it I would like to preserve my Python environment 
I tried deleting plombery.db file that didin't work ...
What should I delete ?

**Comment by lucafaggianelli** [comment]
Yes that's the file to delete if you're using the standard SQLite database. You may also try to delete the data folder containing logs and more. What's the specific error you get?
